Access Control
empowerchain/empowerchain pull request #334
Opened 2022-11-23 15:44 UTC by ba1ciu

2022-11-23 16:43 UTC, bjaanes requested changes
Some thoughts on the design. I like the general concept, but I would prefer to keep it more in line with typical SDK design of passing keepers and using interfaces (expected keepers type of thing)

2022-11-23 16:43 UTC, bjaanes commented on chain/app/app.go
> +		app.GetPermStore(accesscontrolmoduletypes.ModuleName),
This should send in the keeper, right?

2022-11-23 16:43 UTC, bjaanes commented on chain/x/accesscontrol/types/perm_store.go
> +package types
This file makes me a little uncomfortable, because it deals with storage and stores and stuff outside of the keeper (go)module. I think it would be more correct to get this into the keeper in some way and send the keeper to the modules who are going to use this.

2022-11-23 16:43 UTC, bjaanes commented on chain/x/accesscontrol/keeper/keeper.go
> +		panic("perm store already occupied")
More returning of errors and less panics, wtyd?

2022-11-23 16:44 UTC, bjaanes commented
Oh, and spec documentation would be good :)

2022-11-27 15:39 UTC, ba1ciu commented on chain/x/accesscontrol/types/perm_store.go
> +package types
All storage op moved to keeper.

2022-11-27 15:41 UTC, ba1ciu commented on chain/x/accesscontrol/keeper/keeper.go
> +		panic("perm store already occupied")
Moved to subkeeper's initSubStore(). I'd personally leave it like that as SubKeeper is ought to be initialized only during app initialization in app.go

2022-11-27 15:42 UTC, ba1ciu commented on chain/app/app.go
> +		app.GetPermStore(accesscontrolmoduletypes.ModuleName),
Now SubKeeper is initialized and injected.

2022-11-27 17:18 UTC, gjermundgaraba requested changes
Looks good, mostly just some questions we can go through on Monday

2022-11-27 17:18 UTC, gjermundgaraba commented on chain/app/test_helpers.go
> +	sk = append(sk, accesscontrolmodulekeeper.NewSubKeeper(keeper, "mockmodule1"))
Do they have to be initialized?
I'm just wondering if it is less error-prone if they are just lazily initialized?

2022-11-27 17:18 UTC, gjermundgaraba commented on chain/proto/empowerchain/accesscontrol/query.proto
> +service Query {
Would it make more sense to just not have these empty proto files if they are not really needed?

2022-11-27 17:18 UTC, gjermundgaraba commented on chain/x/accesscontrol/keeper/keeper.go
> +func (k Keeper) IteratePermissions(ctx sdk.Context, subKey string,
If this is only for genesis export, can it not be private?

2022-11-27 17:18 UTC, gjermundgaraba commented on chain/x/accesscontrol/keeper/sub_keeper.go
> +	kaddr  string
These names are very hard to parse and understand. Perhaps it might be better to give them more descriptive names?

2022-11-27 17:18 UTC, gjermundgaraba commented on chain/x/accesscontrol/module.go
> +	return nil
Is nil valid here?

2022-11-27 17:18 UTC, gjermundgaraba commented on chain/x/accesscontrol/types/keys.go
> +	// Workaround for key collision
Can you explain this a bit more?

2022-11-28 12:23 UTC, ba1ciu commented on chain/proto/empowerchain/accesscontrol/query.proto
> +service Query {
Yes. I deleted protos and querier + msg server.

2022-11-28 12:23 UTC, ba1ciu commented on chain/x/accesscontrol/keeper/keeper.go
> +func (k Keeper) IteratePermissions(ctx sdk.Context, subKey string,
Fixed

2022-11-28 12:23 UTC, ba1ciu commented on chain/x/accesscontrol/keeper/sub_keeper.go
> +	kaddr  string
Leftover from debugging. Deleted.

2022-11-28 12:23 UTC, ba1ciu commented on chain/x/accesscontrol/module.go
> +	return nil
Fixed.

2022-11-28 12:23 UTC, ba1ciu commented on chain/x/accesscontrol/types/keys.go
> +	// Workaround for key collision
Added a comment.

2022-11-28 12:45 UTC, gjermundgaraba requested changes
Conflicts that needs to be solved, but otherwise good

2022-11-28 21:22 UTC, merged