323 credit issuance
empowerchain/empowerchain pull request #350
Opened 2022-12-01 16:59 UTC by ba1ciu

2022-12-01 19:01 UTC, gjermundgaraba requested changes

2022-12-02 10:22 UTC, ba1ciu commented on chain/proto/empowerchain/plasticcredit/types.proto
>    uint64 project_id = 2;
No, the "denom" is ID here.

2022-12-02 10:29 UTC, ba1ciu commented on chain/x/plasticcredit/msgs.go
> +func (m *MsgIssueCredits) ValidateBasic() error {
On it.

2022-12-02 10:31 UTC, ba1ciu commented on chain/x/plasticcredit/msgs.go
> +		return errors.Wrap(ErrInvalidProjectID, "invalid project id")
For msg types validation - I agree, makes sense. Will refactor accordingly.

2022-12-02 10:50 UTC, ba1ciu commented on chain/proto/empowerchain/plasticcredit/tx.proto
> +  CreditBalance credit_amount = 4;
It's this way basically to allow for issuing credits that are already retired. Not sure if we need such, but I saw that it's possible on Regen.

2022-12-02 10:51 UTC, ba1ciu commented on chain/proto/empowerchain/plasticcredit/types.proto
> +  string denom = 1;
This was my idea of creating different types that also contain keys, but as we now decided to include keys into the store objects, I'm deleting those IDxxx objects.

2022-12-02 11:06 UTC, gjermundgaraba commented on chain/proto/empowerchain/plasticcredit/types.proto
>    uint64 project_id = 2;
Yeah, I realized eventually :D

2022-12-02 11:07 UTC, gjermundgaraba commented on chain/proto/empowerchain/plasticcredit/tx.proto
> +  CreditBalance credit_amount = 4;
Let's keep it simple until we know we need it.

2022-12-02 14:18 UTC, gjermundgaraba approved these changes

2022-12-02 14:20 UTC, merged