Issue credit test
empowerchain/empowerchain pull request #371
Opened 2022-12-07 13:40 UTC by ba1ciu

2022-12-07 14:00 UTC, gjermundgaraba requested changes

2022-12-07 14:00 UTC, gjermundgaraba commented on chain/x/plasticcredit/keeper/msg_server_test.go
> +				s.Require().Equal(tc.expectedBalanceRetired, balance.Balance.Retired)
Maybe also test that active changes.
And perhaps that the amount in the collection is still correct

2022-12-07 14:00 UTC, gjermundgaraba commented on chain/x/plasticcredit/keeper/msg_server_test.go
> +				s.Require().Equal(tc.expectedSenderBalance, senderBalance.Balance.Active)
In the case of retire true, is the collection updated correctly too?

2022-12-07 14:00 UTC, gjermundgaraba commented on chain/x/plasticcredit/spec/02_state.md
> +# State
This file should not be in the PR. This has been moved to x/plasticcredit/README.md

2022-12-07 15:07 UTC, ba1ciu commented on chain/x/plasticcredit/keeper/msg_server_test.go
> +		"empty serial number": {
Yeah, I know. The thing is that, if those tests aren't run through the actual network, ValidateBasic isn't invoked and I didn't want to double the validation.

2022-12-07 15:10 UTC, ba1ciu commented on chain/x/plasticcredit/keeper/msg_server_test.go
> +				s.Require().Equal(tc.expectedAmount, resp.Collection.TotalAmount.Active)
Yeah, checking all 3 makes sense. Will do.

2022-12-07 15:26 UTC, gjermundgaraba commented on chain/x/plasticcredit/keeper/msg_server_test.go
> +		"empty serial number": {
True, but does that mean that it is currently possible to mistakenly issue 0 credits if for instance called from a different module (which would not trigger ValidateBasic)?

2022-12-07 16:42 UTC, ba1ciu commented on chain/x/plasticcredit/keeper/msg_server_test.go
> +		"empty serial number": {
Issuance can be performed through msgServer only atm.
In this particular we can get the error on the Validate() level. Will fix that.

2022-12-07 17:51 UTC, gjermundgaraba requested changes
One small thing + you need to merge in main to resolve the conflict

2022-12-07 17:51 UTC, gjermundgaraba commented on chain/x/plasticcredit/keeper/msg_server_test.go
> +				s.Require().Equal(tc.expectedAmount, resp.Collection.TotalAmount.Active)
Hmm, should it also check Inactive balance?

2022-12-08 11:10 UTC, ba1ciu commented on chain/x/plasticcredit/keeper/msg_server_test.go
> +				s.Require().Equal(tc.expectedAmount, resp.Collection.TotalAmount.Active)
Yeah, but I wouldn't test it with fetching before and after balance like for transfer as the balance might not exist yet (and it returns error instead of 0 balance (maybe it's something to change, so it works like bank and returns 0 balance?)).
Issuance shouldn't  create any new retired credits so I just added comparing to 0.

2022-12-08 11:30 UTC, gjermundgaraba approved these changes

2022-12-08 11:30 UTC, gjermundgaraba commented on chain/x/plasticcredit/keeper/msg_server_test.go
> +				s.Require().Equal(tc.expectedAmount, resp.Collection.TotalAmount.Active)
Ah, that makes sense. Perfect.

2022-12-08 11:31 UTC, merged